export const NPC_HERO = "npc_dota_hero_"
export const ICON_EXTENSION = "_icon.png"
export const MODEL_EXTENSION = "_model.png"
export const VERT_EXTENSION = "_vert.png"
export const HORZ_EXTENSION = "_horz.png"